### ISSUE TITLE
eval.py error for S3DIS-S0-N2-K5

### ISSUE THREAD

**Issue by siddharthKatageri** [Na-Z/attMPTI#17]
I am getting the following error while running `train_MPTI.sh` for s=0, n=2, and k=5:
```
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    train(args)
  File "/home2/siddharth/attMPTI/runs/mpti_train.py", line 72, in train
    valid_loss, mean_IoU = test_few_shot(VALID_LOADER, MPTI, logger, VALID_CLASSES)
  File "/home2/siddharth/attMPTI/runs/eval.py", line 101, in test_few_shot
    mean_IoU = evaluate_metric(logger, predicted_label_total, gt_label_total, label2class_total, test_classes)
  File "/home2/siddharth/attMPTI/runs/eval.py", line 66, in evaluate_metric
    iou = true_positive_classes[c] / float(gt_classes[c] + positive_classes[c] - true_positive_classes[c])
ZeroDivisionError: float division by zero
```
the validation classes are: [ 3 11 10  0  8  4]
validation data length: 142
It seems that for classes 0, 8 and 4 the counter in `true_positive_classes`, `gt_classes` and `positive_classes` are 0.
As this error can be avoided by using a condition, I wanted to make sure that there is no fault in the validation dataset, as there is not a single sample from class 0, 8, and 4. Is this normal, or should I regenerate the validation dataset?

**Comment by siddharthKatageri** [comment]
Sorry, the validation files were missing for the directory. I constructed new validation files with for s=0, n=2, and k=5.
