### ISSUE TITLE
eval_attMPTI.sh

### ISSUE THREAD

**Issue by Chengyuelan** [Na-Z/attMPTI#18]
when I was training the 'eval_attMPTI.sh' file, something went wrong:I would be very grateful for your solution.Thanks!
(attMPTI17) excellence@cyy:~/attMPTI-main$ bash /home/attMPTI-main/scripts/eval_attMPTI.sh
/home/attMPTI-main/scripts/eval_attMPTI.sh: line 14: SURE: command not found
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    eval(args)
  File "/home/attMPTI-main/runs/eval.py", line 102, in eval
    logger = init_logger(args.log_dir, args)
  File "/home/attMPTI-main/utils/logger.py", line 34, in init_logger
    mkdir(log_dir)
  File "/home/attMPTI-main/utils/logger.py", line 22, in mkdir
    os.makedirs(path)
  File "/home/anaconda3/envs/attMPTI17/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by siddharthKatageri** [comment]
Hi @Chengyuelan,
I got the same error while running.
The issue is `log_dir` gets an empty string.
In `eval_MPTI.sh` remove the comment in front of `MODEL_CHECKPOINT` in line 14. Doing this resolved the issue for me.

**Comment by Na-Z** [comment]
The problem is fixed. Pls check the latest version.
