### ISSUE TITLE
from torch-cluster import fps报错

### ISSUE THREAD

**Issue by AaronNZH** [Na-Z/attMPTI#24]
from torch-cluster import fps报错，其他模块均按照readme要求安装

pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html安装失败，无法找到对应包，所以直接使用的对应版本链接whel安装 pip install https://data.pyg.org/whl/torch-1.5.0/torch_cluster-latest%2Bcu101-cp36-cp36m-linux_x86_64.whl

但是运行时报错找不到模块
(torch1.4.0) ubuntu@ubuntu-System-Product-Name:/data/NZH/attMPTI-main$ bash scripts/train_attMPTI.sh
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    from runs.mpti_train import train
  File "/data/NZH/attMPTI-main/runs/mpti_train.py", line 10, in <module>
    from runs.eval import test_few_shot
  File "/data/NZH/attMPTI-main/runs/eval.py", line 14, in <module>
    from models.mpti_learner import MPTILearner
  File "/data/NZH/attMPTI-main/models/mpti_learner.py", line 10, in <module>
    from models.mpti import MultiPrototypeTransductiveInference
  File "/data/NZH/attMPTI-main/models/mpti.py", line 11, in <module>
    from torch_cluster import fps
  File "/home/ubuntu/anaconda3/envs/torch1.4.0/lib/python3.6/site-packages/torch_cluster/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/ubuntu/anaconda3/envs/torch1.4.0/lib/python3.6/site-packages/torch/_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "/home/ubuntu/anaconda3/envs/torch1.4.0/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by AaronNZH** [comment]
Following are work
pytorch 1.13
conda install pytorch-cluster -c pyg
