### ISSUE TITLE
Errors occur when running 'bash train_attMPTI.sh'

### ISSUE THREAD

**Issue by neymar-jr** [Na-Z/attMPTI#26]
Errors are listed as below.

Traceback (most recent call last):
  File "/home/liuxuanchen/Develop/few-shot-point-cloud/attMPTI/main.py", line 101, in <module>
    train(args)
  File "/home/liuxuanchen/Develop/few-shot-point-cloud/attMPTI/runs/mpti_train.py", line 58, in train
    loss, accuracy = MPTI.train(data)
  File "/home/liuxuanchen/Develop/few-shot-point-cloud/attMPTI/models/mpti_learner.py", line 63, in train
    query_logits, loss= self.model(support_x, support_y, query_x, query_y)
  File "/home/liuxuanchen/anaconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/liuxuanchen/Develop/few-shot-point-cloud/attMPTI/models/mpti.py", line 107, in forward
    A = self.calculateLocalConstrainedAffinity(node_feat, k=self.k_connect)
  File "/home/liuxuanchen/Develop/few-shot-point-cloud/attMPTI/models/mpti.py", line 258, in calculateLocalConstrainedAffinity
    A = A.scatter_(1, I, knn_similarity)
RuntimeError: Expected index [4396, 200] to be smaller than self [4396, 4396] apart from dimension 1 and to be smaller size than src [4396, 192]

**Comment by mayurmankar-dev** [comment]
I am also getting exactly same error.

**Comment by XinruTeng** [comment]
Hello, I also encountered some errors when running 'bash train_attMPTI.sh', the error is shown below：
Traceback (most recent call last):
  File "I:\Download\attMPTI-main\utils\checkpoint_util.py", line 28, in load_model_checkpoint
    start_iter  = checkpoint['iteration']
KeyError: 'iteration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\Download\attMPTI-main\main.py", line 101, in <module>
    train(args)
  File "I:\Download\attMPTI-main\runs\mpti_train.py", line 25, in train
    MPTI = MPTILearner(args)
  File "I:\Download\attMPTI-main\models\mpti_learner.py", line 42, in __init__
    self.model, self.optimizer = load_model_checkpoint(self.model, args.model_checkpoint_path,
  File "I:\Download\attMPTI-main\utils\checkpoint_util.py", line 31, in load_model_checkpoint
    raise ValueError('Model checkpoint file must be correctly given (%s).' %model_checkpoint_path)
ValueError: Model checkpoint file must be correctly given (I:\Download\attMPTI-main\datasets\log_s3dis\log_pretrain_s3dis_S0\).
I don't know how to fix this at the moment.

**Comment by suurajroshan** [comment]
I get a similar error too. Did anyone get a solution to this error?

**Comment by WeiTang-code** [comment]
It may be something wrong with faiss. I've managed to run the code successfully in another environment, but it gives me an error in a higher version of pytorch and cuda environment on a 30-series GPU. Now I get wrong knn_index.

---

Further troubleshooting revealed that it was not a faiss error, but a large number of "nan" in the tensor of node_feat, which comes from the prototype.

---

I have solved this problem. It comes from the function "pytorch.nn.functional.pairwise_distance". This function behaves differently in different versions of pytorch.

If you use pytorch of higher version, you can refer to my solution. Note that every use of the "pairwise_distance" function requires modification.

` distances = F.pairwise_distance(feat[..., None].transpose(1,2), farthest_seeds[None, ...],
                                            p=2)  # (n_points, n_prototypes)`

**Comment by xin1106** [comment]
@WeiTang-code Your answer is very helpful. 
I encountered an error while running the protonet.by : 
Runtime Error: Expected target size [2,192], got [2,2048]. 
Have you encountered this problem before. 
For the 'similarity=- F.pairise_distance (feature, prototype [None, None], p=2)**2'， how should I modify it?

**Comment by good-est** [comment]
Here are my adjustions on mpti.py. First, I replace the "distances = F.pairwise_distance(feat[..., None], farthest_seeds.transpose(0, 1)[None, ...], p=2)  # (n_points, n_prototypes)“ in line 152 with “distances = F.pairwise_distance(feat[..., None].transpose(1,2), farthest_seeds[None, ...], p=2)  # (n_points, n_prototypes)”. Second, I replece the "dist = F.pairwise_distance(node_feat[:,:,None], knn_feat.transpose(1,2), p=2)“ in line 251 with “dist = torch.cdist(node_feat.unsqueeze(1),knn_feat,p=2).squeeze(1)”.
